// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiscoIpsum.Data;

namespace WiscoIpsum.Migrations
{
    [DbContext(typeof(WiscoIpsumContext))]
    [Migration("20191112045226_AddCacheSchema")]
    partial class AddCacheSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WiscoIpsum.Models.Phrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phrase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Ope"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Where-Abouts"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Spotted Cow"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Brandy Old Fashioned"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Stop-and-go-lights"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Fleet Farm"
                        },
                        new
                        {
                            Id = 7,
                            Text = "Cheesehead"
                        },
                        new
                        {
                            Id = 8,
                            Text = "Fish Fry"
                        },
                        new
                        {
                            Id = 9,
                            Text = "Bubbler"
                        },
                        new
                        {
                            Id = 10,
                            Text = "Aw Geez"
                        },
                        new
                        {
                            Id = 11,
                            Text = "For Cripes Sakes"
                        },
                        new
                        {
                            Id = 12,
                            Text = "Up Nort"
                        },
                        new
                        {
                            Id = 13,
                            Text = "Uff-Da"
                        },
                        new
                        {
                            Id = 14,
                            Text = "Ya Know?"
                        },
                        new
                        {
                            Id = 15,
                            Text = "Believe You Me"
                        },
                        new
                        {
                            Id = 16,
                            Text = "You betcha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
